language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -k "$deployKeyEncryptionKey" -in deployment/deploy_key.pem.enc
  -out deployment/deploy_key.pem -d
- chmod +x gradlew
- chmod +x deployment/deploy.sh
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  email: false
install: echo "Skip assemble"
script: "./gradlew build --continue --stacktrace"
after_success:
- cd deployment/
- source deploy.sh
addons:
  apt:
    packages:
    - oracle-java8-installer
env:
  global:
    secure: XOVOM+3LbRuNpHkwWuFH4PwMCo3cap5s0gLnBFigKC6iiFYdpYu4ZhhQrJI9AnPVULhOH0xOOFOnv7SuBgRUEf/6j7Fb65th/eRUEVjd9LwAMnyycIrmio1FJMMoWTS8jQfYTvErZgXMJu8aWziRctYpN/wLFLZkqJi/XDtVAMU=
